### ISSUE TITLE
Recent faraday-httpclient major version bump breaks Circle changelog builds

### ISSUE THREAD

**Issue by lynchmattj** [onimur/circleci-github-changelog-generator#4]
Our changelog Circle builds recently started failing with the below error:

```
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- httpclient (LoadError)
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/faraday-httpclient-2.0.0/lib/faraday/httpclient.rb:3:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/faraday-1.9.0/lib/faraday.rb:39:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:1:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `block in <top (required)>'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `each'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/connection.rb:1:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/client.rb:1:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit.rb:1:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/github_changelog_generator-1.16.4/lib/github_changelog_generator.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/github_changelog_generator-1.16.4/bin/github_changelog_generator:4:in `require_relative'
	from /usr/local/bundle/gems/github_changelog_generator-1.16.4/bin/github_changelog_generator:4:in `<top (required)>'
	from /usr/local/bundle/bin/github_changelog_generator:25:in `load'
	from /usr/local/bundle/bin/github_changelog_generator:25:in `<main>'
```

It seems like faraday recently bumped major versions from `1.0.1` to `2.0.0`: https://github.com/lostisland/faraday-httpclient/compare/v1.0.1...v2.0.0 

Possible that the major version bump is causing this to fail?

Version of the plugin I'm using: `github-changelog-generator: onimur/github-changelog-generator@2.1.9`

**Comment by justinbchan** [comment]
Should be fixed via https://github.com/lostisland/faraday-httpclient/releases/tag/v2.0.1

**Comment by lynchmattj** [comment]
Yep, confirmed.  Thanks @justinbchan

**Comment by onimur** [comment]
> 

sorry, I currently have no time to work on the project, but i will update the dependencies soon.
